### ISSUE TITLE
Flashlight color

### ISSUE THREAD

**Issue by STVGecko** [FossifyOrg/Flashlight#10]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Flashlight/issues) or [closed](https://github.com/FossifyOrg/Flashlight/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Flashlight/discussions) or [closed](https://github.com/FossifyOrg/Flashlight/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Flashlight/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Can you add the possibility to change the color of the flashlight (RGB, obviously)

### Why do you want this feature?

A little of app have this feature but are full of advertising. Secondly, the blue color flashlight is bad for eyes. In the case of a red flashlight, this is a good solution for mountain walks.

**Comment by Aga-C** [comment]
There's already an option to change the screen color. For the flashlight on the back of your phone, there's no possibility to change the color.
